-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;
USE ecommerce_db;

-- ADDING TABLES
CREATE TABLE Category (
    id INTEGER NOT NULL AUTO_INCREMENT,
    category_name VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Product (
    id INTEGER NOT NULL AUTO_INCREMENT,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL NOT NULL,
    stock INTEGER NOT NULL DEFAULT(10),
    category_id INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE Tag (
    id INTEGER NOT NULL AUTO_INCREMENT,
    tag_name VARCHAR(30),
    PRIMARY KEY (id)
);

CREATE TABLE ProductTag (
    id INTEGER NOT NULL AUTO_INCREMENT,
    product_id INTEGER,
    tag_id INTEGER,
    PRIMARY KEY (id)
);